
#cloud-config
# Update and upgrade packages
repo_update: true
repo_upgrade: all
packages:
- python-pip
- ec2-api-tools
runcmd:
- echo "*         hard    nofile      500000" >> /etc/security/limits.conf
- echo "*         soft    nofile      500000" >> /etc/security/limits.conf
- echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
- echo "net.ipv4.tcp_tw_reuse = 1" >> /etc/sysctl.conf
- echo "net.ipv4.tcp_tw_recycle = 1" >> /etc/sysctl.conf
- echo "net.ipv4.tcp_fin_timeout = 1" >> /etc/sysctl.conf
- sysctl -p /etc/sysctl.conf
- /usr/bin/pip install awscli
- ln -s /usr/local/bin/aws /usr/bin/aws
- REGION=`/usr/bin/ec2metadata | grep "^availability-zone:" | awk '{print substr($2, 1, length($2)-1)}'`
- aws configure set default.region $REGION
- aws configure set default.output text
- mkdir /etc/rabbitmq /var/lib/rabbitmq
- >
  echo "XYZABCDFGHIJKLMNOUPQ" > /var/lib/rabbitmq/.erlang.cookie
- chown rabbitmq.rabbitmq /var/lib/rabbitmq -R
- chown rabbitmq.rabbitmq /etc/rabbitmq -R
- chmod og-r /var/lib/rabbitmq/.erlang.cookie
- chmod u+r /var/lib/rabbitmq/.erlang.cookie
- >
  echo 'deb http://www.rabbitmq.com/debian/ testing main' | tee /etc/apt/sources.list.d/rabbitmq.list
- >
  wget -O- https://www.rabbitmq.com/rabbitmq-release-signing-key.asc | apt-key add -
- >
  apt-get update && apt-get -y install rabbitmq-server
- systemctl stop rabbitmq-server.service
- >
  rm -fr /var/lib/rabbitmq/*
- systemctl start rabbitmq-server.service
# Get the rabbitmq clustering and aws plugins..
- wget -O /tmp/rabbitmq_aws-0.10.0.ez https://github.com/rabbitmq/rabbitmq-autocluster/releases/download/0.10.0/rabbitmq_aws-0.10.0.ez
- wget -O /tmp/autocluster-0.10.0.ez https://github.com/rabbitmq/rabbitmq-autocluster/releases/download/0.10.0/autocluster-0.10.0.ez
- >
  cp -f /tmp/*.ez /usr/lib/rabbitmq/lib/rabbitmq_server-*/plugins/
# now enable them into the current rabbitmq installation.
- rabbitmq-plugins enable autocluster rabbitmq_mqtt rabbitmq_web_mqtt rabbitmq_management rabbitmq_management_agent
- >
  echo "[{rabbit, [{log_levels, [{autocluster, info}, {connection, info}]}]},{autocluster, [{backend, aws},{aws_autoscaling, true},{aws_ec2_region, \"$REGION\"},{cluster_cleanup, true},{cleanup_warn_only, false}]}]." > /etc/rabbitmq/rabbitmq.config
- chown rabbitmq.rabbitmq /etc/rabbitmq/rabbitmq.config
- systemctl restart rabbitmq-server.service
# Add a new vhost
- /usr/sbin/rabbitmqctl add_vhost /main/
# Add a new admin user
- /usr/sbin/rabbitmqctl add_user admin Asd123!
- /usr/sbin/rabbitmqctl set_user_tags admin administrator
- /usr/sbin/rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"
- /usr/sbin/rabbitmqctl set_permissions -p /main/ admin ".*" ".*" ".*"
- /usr/sbin/rabbitmqctl add_user dubizzle Asd123!
- /usr/sbin/rabbitmqctl set_user_tags dubizzle celery
- /usr/sbin/rabbitmqctl set_permissions -p /main/ dubizzle ".*" ".*" ".*"
- >
  /usr/sbin/rabbitmqctl set_policy -p / qml-policy ".*" '{"queue-master-locator":"random"}'
- >
  /usr/sbin/rabbitmqctl set_policy -p /main/ uae-policy ".*" '{"queue-master-locator":"random", "ha-mode": "all", "ha-sync-mode": "automatic"}'
- /usr/sbin/rabbitmqctl delete_user guest